# Generated by Django 3.2.9 on 2021-11-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porduct',
            new_name='Product',
        ),
    ]
